/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as PriceRevisionsRouteImport } from './routes/price-revisions'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurrentAccountsRouteImport } from './routes/current-accounts'
import { Route as CounterpartiesRouteImport } from './routes/counterparties'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BusinessLinesRouteImport } from './routes/business-lines'
import { Route as BankImportRouteImport } from './routes/bank-import'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PriceRevisionsIndexRouteImport } from './routes/price-revisions.index'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as TransactionsNewRouteImport } from './routes/transactions.new'
import { Route as RecurringNewRouteImport } from './routes/recurring.new'
import { Route as PriceRevisionsNewRouteImport } from './routes/price-revisions.new'
import { Route as PriceRevisionsIdRouteImport } from './routes/price-revisions.$id'
import { Route as CurrentAccountsNewRouteImport } from './routes/current-accounts.new'
import { Route as CounterpartiesNewRouteImport } from './routes/counterparties.new'
import { Route as ContractsNewRouteImport } from './routes/contracts.new'
import { Route as CompaniesNewRouteImport } from './routes/companies.new'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as CategoriesNewRouteImport } from './routes/categories.new'
import { Route as BusinessLinesNewRouteImport } from './routes/business-lines.new'
import { Route as UsersIdUpdateRouteImport } from './routes/users.$id.update'
import { Route as UsersIdUnbanRouteImport } from './routes/users.$id.unban'
import { Route as UsersIdDeleteRouteImport } from './routes/users.$id.delete'
import { Route as UsersIdBanRouteImport } from './routes/users.$id.ban'
import { Route as RecurringIdEditRouteImport } from './routes/recurring.$id.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceRevisionsRoute = PriceRevisionsRouteImport.update({
  id: '/price-revisions',
  path: '/price-revisions',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAccountsRoute = CurrentAccountsRouteImport.update({
  id: '/current-accounts',
  path: '/current-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterpartiesRoute = CounterpartiesRouteImport.update({
  id: '/counterparties',
  path: '/counterparties',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLinesRoute = BusinessLinesRouteImport.update({
  id: '/business-lines',
  path: '/business-lines',
  getParentRoute: () => rootRouteImport,
} as any)
const BankImportRoute = BankImportRouteImport.update({
  id: '/bank-import',
  path: '/bank-import',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceRevisionsIndexRoute = PriceRevisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PriceRevisionsRoute,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransactionsRoute,
} as any)
const RecurringNewRoute = RecurringNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecurringRoute,
} as any)
const PriceRevisionsNewRoute = PriceRevisionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PriceRevisionsRoute,
} as any)
const PriceRevisionsIdRoute = PriceRevisionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PriceRevisionsRoute,
} as any)
const CurrentAccountsNewRoute = CurrentAccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CurrentAccountsRoute,
} as any)
const CounterpartiesNewRoute = CounterpartiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CounterpartiesRoute,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContractsRoute,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompaniesRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CategoriesRoute,
} as any)
const BusinessLinesNewRoute = BusinessLinesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BusinessLinesRoute,
} as any)
const UsersIdUpdateRoute = UsersIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdUnbanRoute = UsersIdUnbanRouteImport.update({
  id: '/$id/unban',
  path: '/$id/unban',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdDeleteRoute = UsersIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdBanRoute = UsersIdBanRouteImport.update({
  id: '/$id/ban',
  path: '/$id/ban',
  getParentRoute: () => UsersRoute,
} as any)
const RecurringIdEditRoute = RecurringIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => RecurringRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/bank-import': typeof BankImportRoute
  '/business-lines': typeof BusinessLinesRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/counterparties': typeof CounterpartiesRouteWithChildren
  '/current-accounts': typeof CurrentAccountsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/price-revisions': typeof PriceRevisionsRouteWithChildren
  '/receivables': typeof ReceivablesRoute
  '/recurring': typeof RecurringRouteWithChildren
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/business-lines/new': typeof BusinessLinesNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/contracts/new': typeof ContractsNewRoute
  '/counterparties/new': typeof CounterpartiesNewRoute
  '/current-accounts/new': typeof CurrentAccountsNewRoute
  '/price-revisions/$id': typeof PriceRevisionsIdRoute
  '/price-revisions/new': typeof PriceRevisionsNewRoute
  '/recurring/new': typeof RecurringNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/users/new': typeof UsersNewRoute
  '/price-revisions/': typeof PriceRevisionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recurring/$id/edit': typeof RecurringIdEditRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/bank-import': typeof BankImportRoute
  '/business-lines': typeof BusinessLinesRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/counterparties': typeof CounterpartiesRouteWithChildren
  '/current-accounts': typeof CurrentAccountsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/recurring': typeof RecurringRouteWithChildren
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/business-lines/new': typeof BusinessLinesNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/contracts/new': typeof ContractsNewRoute
  '/counterparties/new': typeof CounterpartiesNewRoute
  '/current-accounts/new': typeof CurrentAccountsNewRoute
  '/price-revisions/$id': typeof PriceRevisionsIdRoute
  '/price-revisions/new': typeof PriceRevisionsNewRoute
  '/recurring/new': typeof RecurringNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/users/new': typeof UsersNewRoute
  '/price-revisions': typeof PriceRevisionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recurring/$id/edit': typeof RecurringIdEditRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/bank-import': typeof BankImportRoute
  '/business-lines': typeof BusinessLinesRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/counterparties': typeof CounterpartiesRouteWithChildren
  '/current-accounts': typeof CurrentAccountsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/price-revisions': typeof PriceRevisionsRouteWithChildren
  '/receivables': typeof ReceivablesRoute
  '/recurring': typeof RecurringRouteWithChildren
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/business-lines/new': typeof BusinessLinesNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/contracts/new': typeof ContractsNewRoute
  '/counterparties/new': typeof CounterpartiesNewRoute
  '/current-accounts/new': typeof CurrentAccountsNewRoute
  '/price-revisions/$id': typeof PriceRevisionsIdRoute
  '/price-revisions/new': typeof PriceRevisionsNewRoute
  '/recurring/new': typeof RecurringNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/users/new': typeof UsersNewRoute
  '/price-revisions/': typeof PriceRevisionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recurring/$id/edit': typeof RecurringIdEditRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/bank-import'
    | '/business-lines'
    | '/categories'
    | '/clients'
    | '/companies'
    | '/contracts'
    | '/counterparties'
    | '/current-accounts'
    | '/dashboard'
    | '/login'
    | '/payables'
    | '/price-revisions'
    | '/receivables'
    | '/recurring'
    | '/signup'
    | '/transactions'
    | '/users'
    | '/business-lines/new'
    | '/categories/new'
    | '/clients/new'
    | '/companies/new'
    | '/contracts/new'
    | '/counterparties/new'
    | '/current-accounts/new'
    | '/price-revisions/$id'
    | '/price-revisions/new'
    | '/recurring/new'
    | '/transactions/new'
    | '/users/new'
    | '/price-revisions/'
    | '/api/auth/$'
    | '/recurring/$id/edit'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/bank-import'
    | '/business-lines'
    | '/categories'
    | '/clients'
    | '/companies'
    | '/contracts'
    | '/counterparties'
    | '/current-accounts'
    | '/dashboard'
    | '/login'
    | '/payables'
    | '/receivables'
    | '/recurring'
    | '/signup'
    | '/transactions'
    | '/users'
    | '/business-lines/new'
    | '/categories/new'
    | '/clients/new'
    | '/companies/new'
    | '/contracts/new'
    | '/counterparties/new'
    | '/current-accounts/new'
    | '/price-revisions/$id'
    | '/price-revisions/new'
    | '/recurring/new'
    | '/transactions/new'
    | '/users/new'
    | '/price-revisions'
    | '/api/auth/$'
    | '/recurring/$id/edit'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/bank-import'
    | '/business-lines'
    | '/categories'
    | '/clients'
    | '/companies'
    | '/contracts'
    | '/counterparties'
    | '/current-accounts'
    | '/dashboard'
    | '/login'
    | '/payables'
    | '/price-revisions'
    | '/receivables'
    | '/recurring'
    | '/signup'
    | '/transactions'
    | '/users'
    | '/business-lines/new'
    | '/categories/new'
    | '/clients/new'
    | '/companies/new'
    | '/contracts/new'
    | '/counterparties/new'
    | '/current-accounts/new'
    | '/price-revisions/$id'
    | '/price-revisions/new'
    | '/recurring/new'
    | '/transactions/new'
    | '/users/new'
    | '/price-revisions/'
    | '/api/auth/$'
    | '/recurring/$id/edit'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  BankImportRoute: typeof BankImportRoute
  BusinessLinesRoute: typeof BusinessLinesRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ContractsRoute: typeof ContractsRouteWithChildren
  CounterpartiesRoute: typeof CounterpartiesRouteWithChildren
  CurrentAccountsRoute: typeof CurrentAccountsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PayablesRoute: typeof PayablesRoute
  PriceRevisionsRoute: typeof PriceRevisionsRouteWithChildren
  ReceivablesRoute: typeof ReceivablesRoute
  RecurringRoute: typeof RecurringRouteWithChildren
  SignupRoute: typeof SignupRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-revisions': {
      id: '/price-revisions'
      path: '/price-revisions'
      fullPath: '/price-revisions'
      preLoaderRoute: typeof PriceRevisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-accounts': {
      id: '/current-accounts'
      path: '/current-accounts'
      fullPath: '/current-accounts'
      preLoaderRoute: typeof CurrentAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counterparties': {
      id: '/counterparties'
      path: '/counterparties'
      fullPath: '/counterparties'
      preLoaderRoute: typeof CounterpartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-lines': {
      id: '/business-lines'
      path: '/business-lines'
      fullPath: '/business-lines'
      preLoaderRoute: typeof BusinessLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-import': {
      id: '/bank-import'
      path: '/bank-import'
      fullPath: '/bank-import'
      preLoaderRoute: typeof BankImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-revisions/': {
      id: '/price-revisions/'
      path: '/'
      fullPath: '/price-revisions/'
      preLoaderRoute: typeof PriceRevisionsIndexRouteImport
      parentRoute: typeof PriceRevisionsRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/recurring/new': {
      id: '/recurring/new'
      path: '/new'
      fullPath: '/recurring/new'
      preLoaderRoute: typeof RecurringNewRouteImport
      parentRoute: typeof RecurringRoute
    }
    '/price-revisions/new': {
      id: '/price-revisions/new'
      path: '/new'
      fullPath: '/price-revisions/new'
      preLoaderRoute: typeof PriceRevisionsNewRouteImport
      parentRoute: typeof PriceRevisionsRoute
    }
    '/price-revisions/$id': {
      id: '/price-revisions/$id'
      path: '/$id'
      fullPath: '/price-revisions/$id'
      preLoaderRoute: typeof PriceRevisionsIdRouteImport
      parentRoute: typeof PriceRevisionsRoute
    }
    '/current-accounts/new': {
      id: '/current-accounts/new'
      path: '/new'
      fullPath: '/current-accounts/new'
      preLoaderRoute: typeof CurrentAccountsNewRouteImport
      parentRoute: typeof CurrentAccountsRoute
    }
    '/counterparties/new': {
      id: '/counterparties/new'
      path: '/new'
      fullPath: '/counterparties/new'
      preLoaderRoute: typeof CounterpartiesNewRouteImport
      parentRoute: typeof CounterpartiesRoute
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof ContractsRoute
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/categories/new': {
      id: '/categories/new'
      path: '/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/business-lines/new': {
      id: '/business-lines/new'
      path: '/new'
      fullPath: '/business-lines/new'
      preLoaderRoute: typeof BusinessLinesNewRouteImport
      parentRoute: typeof BusinessLinesRoute
    }
    '/users/$id/update': {
      id: '/users/$id/update'
      path: '/$id/update'
      fullPath: '/users/$id/update'
      preLoaderRoute: typeof UsersIdUpdateRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/unban': {
      id: '/users/$id/unban'
      path: '/$id/unban'
      fullPath: '/users/$id/unban'
      preLoaderRoute: typeof UsersIdUnbanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/delete': {
      id: '/users/$id/delete'
      path: '/$id/delete'
      fullPath: '/users/$id/delete'
      preLoaderRoute: typeof UsersIdDeleteRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/ban': {
      id: '/users/$id/ban'
      path: '/$id/ban'
      fullPath: '/users/$id/ban'
      preLoaderRoute: typeof UsersIdBanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/recurring/$id/edit': {
      id: '/recurring/$id/edit'
      path: '/$id/edit'
      fullPath: '/recurring/$id/edit'
      preLoaderRoute: typeof RecurringIdEditRouteImport
      parentRoute: typeof RecurringRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BusinessLinesRouteChildren {
  BusinessLinesNewRoute: typeof BusinessLinesNewRoute
}

const BusinessLinesRouteChildren: BusinessLinesRouteChildren = {
  BusinessLinesNewRoute: BusinessLinesNewRoute,
}

const BusinessLinesRouteWithChildren = BusinessLinesRoute._addFileChildren(
  BusinessLinesRouteChildren,
)

interface CategoriesRouteChildren {
  CategoriesNewRoute: typeof CategoriesNewRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesNewRoute: CategoriesNewRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ClientsRouteChildren {
  ClientsNewRoute: typeof ClientsNewRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsNewRoute: ClientsNewRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface CompaniesRouteChildren {
  CompaniesNewRoute: typeof CompaniesNewRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesNewRoute: CompaniesNewRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ContractsRouteChildren {
  ContractsNewRoute: typeof ContractsNewRoute
}

const ContractsRouteChildren: ContractsRouteChildren = {
  ContractsNewRoute: ContractsNewRoute,
}

const ContractsRouteWithChildren = ContractsRoute._addFileChildren(
  ContractsRouteChildren,
)

interface CounterpartiesRouteChildren {
  CounterpartiesNewRoute: typeof CounterpartiesNewRoute
}

const CounterpartiesRouteChildren: CounterpartiesRouteChildren = {
  CounterpartiesNewRoute: CounterpartiesNewRoute,
}

const CounterpartiesRouteWithChildren = CounterpartiesRoute._addFileChildren(
  CounterpartiesRouteChildren,
)

interface CurrentAccountsRouteChildren {
  CurrentAccountsNewRoute: typeof CurrentAccountsNewRoute
}

const CurrentAccountsRouteChildren: CurrentAccountsRouteChildren = {
  CurrentAccountsNewRoute: CurrentAccountsNewRoute,
}

const CurrentAccountsRouteWithChildren = CurrentAccountsRoute._addFileChildren(
  CurrentAccountsRouteChildren,
)

interface PriceRevisionsRouteChildren {
  PriceRevisionsIdRoute: typeof PriceRevisionsIdRoute
  PriceRevisionsNewRoute: typeof PriceRevisionsNewRoute
  PriceRevisionsIndexRoute: typeof PriceRevisionsIndexRoute
}

const PriceRevisionsRouteChildren: PriceRevisionsRouteChildren = {
  PriceRevisionsIdRoute: PriceRevisionsIdRoute,
  PriceRevisionsNewRoute: PriceRevisionsNewRoute,
  PriceRevisionsIndexRoute: PriceRevisionsIndexRoute,
}

const PriceRevisionsRouteWithChildren = PriceRevisionsRoute._addFileChildren(
  PriceRevisionsRouteChildren,
)

interface RecurringRouteChildren {
  RecurringNewRoute: typeof RecurringNewRoute
  RecurringIdEditRoute: typeof RecurringIdEditRoute
}

const RecurringRouteChildren: RecurringRouteChildren = {
  RecurringNewRoute: RecurringNewRoute,
  RecurringIdEditRoute: RecurringIdEditRoute,
}

const RecurringRouteWithChildren = RecurringRoute._addFileChildren(
  RecurringRouteChildren,
)

interface TransactionsRouteChildren {
  TransactionsNewRoute: typeof TransactionsNewRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsNewRoute: TransactionsNewRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

interface UsersRouteChildren {
  UsersNewRoute: typeof UsersNewRoute
  UsersIdBanRoute: typeof UsersIdBanRoute
  UsersIdDeleteRoute: typeof UsersIdDeleteRoute
  UsersIdUnbanRoute: typeof UsersIdUnbanRoute
  UsersIdUpdateRoute: typeof UsersIdUpdateRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersNewRoute: UsersNewRoute,
  UsersIdBanRoute: UsersIdBanRoute,
  UsersIdDeleteRoute: UsersIdDeleteRoute,
  UsersIdUnbanRoute: UsersIdUnbanRoute,
  UsersIdUpdateRoute: UsersIdUpdateRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  BankImportRoute: BankImportRoute,
  BusinessLinesRoute: BusinessLinesRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  CompaniesRoute: CompaniesRouteWithChildren,
  ContractsRoute: ContractsRouteWithChildren,
  CounterpartiesRoute: CounterpartiesRouteWithChildren,
  CurrentAccountsRoute: CurrentAccountsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PayablesRoute: PayablesRoute,
  PriceRevisionsRoute: PriceRevisionsRouteWithChildren,
  ReceivablesRoute: ReceivablesRoute,
  RecurringRoute: RecurringRouteWithChildren,
  SignupRoute: SignupRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
