/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as UsersIdUpdateRouteImport } from './routes/users.$id.update'
import { Route as UsersIdUnbanRouteImport } from './routes/users.$id.unban'
import { Route as UsersIdDeleteRouteImport } from './routes/users.$id.delete'
import { Route as UsersIdBanRouteImport } from './routes/users.$id.ban'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdUpdateRoute = UsersIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdUnbanRoute = UsersIdUnbanRouteImport.update({
  id: '/$id/unban',
  path: '/$id/unban',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdDeleteRoute = UsersIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdBanRoute = UsersIdBanRouteImport.update({
  id: '/$id/ban',
  path: '/$id/ban',
  getParentRoute: () => UsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/recurring': typeof RecurringRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/recurring': typeof RecurringRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/recurring': typeof RecurringRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/payables'
    | '/receivables'
    | '/recurring'
    | '/signup'
    | '/users'
    | '/users/new'
    | '/api/auth/$'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/payables'
    | '/receivables'
    | '/recurring'
    | '/signup'
    | '/users'
    | '/users/new'
    | '/api/auth/$'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/payables'
    | '/receivables'
    | '/recurring'
    | '/signup'
    | '/users'
    | '/users/new'
    | '/api/auth/$'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PayablesRoute: typeof PayablesRoute
  ReceivablesRoute: typeof ReceivablesRoute
  RecurringRoute: typeof RecurringRoute
  SignupRoute: typeof SignupRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/update': {
      id: '/users/$id/update'
      path: '/$id/update'
      fullPath: '/users/$id/update'
      preLoaderRoute: typeof UsersIdUpdateRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/unban': {
      id: '/users/$id/unban'
      path: '/$id/unban'
      fullPath: '/users/$id/unban'
      preLoaderRoute: typeof UsersIdUnbanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/delete': {
      id: '/users/$id/delete'
      path: '/$id/delete'
      fullPath: '/users/$id/delete'
      preLoaderRoute: typeof UsersIdDeleteRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/ban': {
      id: '/users/$id/ban'
      path: '/$id/ban'
      fullPath: '/users/$id/ban'
      preLoaderRoute: typeof UsersIdBanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UsersRouteChildren {
  UsersNewRoute: typeof UsersNewRoute
  UsersIdBanRoute: typeof UsersIdBanRoute
  UsersIdDeleteRoute: typeof UsersIdDeleteRoute
  UsersIdUnbanRoute: typeof UsersIdUnbanRoute
  UsersIdUpdateRoute: typeof UsersIdUpdateRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersNewRoute: UsersNewRoute,
  UsersIdBanRoute: UsersIdBanRoute,
  UsersIdDeleteRoute: UsersIdDeleteRoute,
  UsersIdUnbanRoute: UsersIdUnbanRoute,
  UsersIdUpdateRoute: UsersIdUpdateRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PayablesRoute: PayablesRoute,
  ReceivablesRoute: ReceivablesRoute,
  RecurringRoute: RecurringRoute,
  SignupRoute: SignupRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
